/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp com.Skype.API.Client.xml -a skype_adaptor.h -c SkypeAdaptor -p skype_adaptor.cpp
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SKYPE_ADAPTOR_H_1322212543
#define SKYPE_ADAPTOR_H_1322212543

#include <QtCore/QObject>
#include <QtCore/QMetaObject>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Adaptor class for interface com.Skype.API.Client
 */
class SkypeAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.Skype.API.Client")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.Skype.API.Client\">\n"
"    <method name=\"Notify\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"message\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    SkypeAdaptor(QObject *parent);
    virtual ~SkypeAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Notify(const QString &message);
Q_SIGNALS: // SIGNALS
};

#endif
/*
 * Implementation of adaptor class SkypeAdaptor
 */

SkypeAdaptor::SkypeAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SkypeAdaptor::~SkypeAdaptor()
{
    // destructor
}

void SkypeAdaptor::Notify(const QString &message)
{
    // handle method call com.Skype.API.Client.Notify
    QMetaObject::invokeMethod(parent(), "Notify", Q_ARG(QString, message));
}

